### ISSUE TITLE
Add a Raspberry Pi badge

### ISSUE THREAD

**Issue by OpenBagTwo** [OpenBagTwo/EnderChest#69]
### Is your feature request related to a problem? Please describe.

Nowhere on the README or docs pages does it say that EnderChest works on the Raspberry Pi!

### Describe the solution you'd like

Add a badge with the Raspberry Pi logo to the README and docs pages to go with the Win/mac/Linux/SteamOS badges

### Describe alternatives you've considered

Don't tout the fact that EnderChest works on the Pi?

### Additional context

The real question is whether I can get *minecraft* to still run on the Raspberry Pi...

**Comment by MatterAndy** [comment]
Hello, I just added a PR that solves this issue. This is my first time contributing to an open-source project, so any feedback would be appreciated.
